### ISSUE TITLE
Add mechanism to test locally while developing

### ISSUE THREAD

**Issue by shubhamzanwar** [flipspace/flippie#14]
Create a demo project in a sub directory to check whether the newly developed components work properly. Could explore storybook as a solution

- [ ] Make demo project/setup storybook
- [ ] add the demo project/storybook files in .npmignore
- [ ] Document the local setup in the [contributing guide](https://github.com/shubhamzanwar/flippie/blob/master/.github/CONTRIBUTING.md)

**Comment by mrsauravsahu** [comment]
@shubhamzanwar I could take this up. Can I give it a go?

**Comment by shubhamzanwar** [comment]
Sounds good. Please feel free to :)

**Comment by mrsauravsahu** [comment]
@shubhamzanwar Great. Do assign this to me as I'm not on the contributors list. Yet. 😄

**Comment by mrsauravsahu** [comment]
It's looking pretty!

![Mar-24-2020 00-08-33](https://user-images.githubusercontent.com/9134050/77351378-b0958400-6d63-11ea-8a39-29b9189b6074.gif)

**Comment by mrsauravsahu** [comment]
@shubhamzanwar There's a weird Type Error on the children prop in the component.

https://github.com/mrsauravsahu/flippie/tree/docs/storybook

Changing children to a type of `Element []` works. Let me know what I might be doing wrong.

**Comment by shubhamzanwar** [comment]
Sure. I’ll take a look at it sometime today :)

**Comment by shubhamzanwar** [comment]
@mrsauravsahu https://github.com/flipspace/flippie/pull/17 this PR fixes it.
You can take the latest master pull now. :D
