### ISSUE TITLE
web components: ability to use in a non-react environment?

### ISSUE THREAD

**Issue by mrsauravsahu** [flipspace/flippie#2]
Can this be written as a web component?

**Comment by mrsauravsahu** [comment]
Hey @shubhamzanwar what do you think of this? Assuming the component doesn't have much logic, this might be a really good candidate for a Web Component.

**Comment by shubhamzanwar** [comment]
This is probably out of current scope and we would probably take a look at such a feature if we develop a decently large consumer base for this library
