### ISSUE TITLE
Add slide down card component

### ISSUE THREAD

**Issue by shubhamzanwar** [flipspace/flippie#6]
![image](https://user-images.githubusercontent.com/15626155/77220661-70b67d00-6b68-11ea-8de2-d13d308f8961.png)

The upper card is hidden by default and slides down into the ares when the user hovers over the card

- [ ] Create TS Component
- [ ] Add documentation for the component

**Comment by rohinivsenthil** [comment]
Hey again! Mind if I pick this up?

**Comment by shubhamzanwar** [comment]
Would love all the help possible. Go nuts! xD
